import type { SourceReadiness } from "./domain.ts";

// Owner schedule description for the market pipeline. Unit generation is
// pure; installing/enabling timers is an explicit owner action and nothing
// here starts, enables or claims an already-running scheduler.
//
// Design §5: the market pipeline gets schedule units separate from the
// legacy collect/score/card timers, ordinary reads never trigger collection,
// failures are bounded, and a source task that misses its cutoff freezes a
// partial brief instead of blocking the edition.

export const MARKET_OBSERVE_POLICY = {
  // Two observation slots per day, 12h apart (local time).
  slots_per_day: 2,
  slot_spacing_hours: 12,
  // Bounded read-only collection per source.
  source_timeout_ms: 60_000,
  max_read_retries: 2,
  retry_backoff_ms: [2_000, 8_000],
  global_concurrency: 2,
  // Login failures / captcha never auto-retry; risk control cools down 24h.
  risk_control_cooldown_hours: 24,
} as const;

// Local times stay clear of the legacy collect/score/card morning block so
// the two schedules never fight over the shared SQLite lock.
export const MARKET_SCHEDULE_TIMES = { analyze: "08:50", brief: "09:00" } as const;

export interface MarketScheduleUnits {
  [unitName: string]: string;
}

function onCalendar(time: string): string {
  const m = time.match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return `*-*-* ${time}`;
  return `*-*-* ${String(m[1]).padStart(2, "0")}:${m[2]}:00`;
}

// Units for the locally runnable market pass: analyze the previous complete
// local day, then freeze the brief. `observe` stays a planned stage until a
// source passes qualification and the owner CLI exposes it; generating an
// observe timer before that would schedule a command that must refuse to run.
export function buildMarketScheduleUnits(execStart: string): MarketScheduleUnits {
  const env = [
    `Environment=RADAR_HOME=%h/.short-drama-radar`,
    `Environment="PATH=${(process.env.PATH ?? "/usr/local/bin:/usr/bin:/bin").replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("%", "%%")}"`,
  ].join("\n");
  // Same flock discipline as the legacy units: market services share the
  // radar SQLite file and serialize on the existing lock instead of fighting.
  const service = (name: string, description: string, command: string, after: string[] = []) => `# Generated by radar market schedule install — do not edit by hand.
[Unit]
Description=${description}${after.length > 0 ? `\n${after.map((u) => `After=${u}\nWants=${u}`).join("\n")}` : ""}

[Service]
Type=oneshot
ExecStart=/usr/bin/flock -w 600 %h/.short-drama-radar/radar.lock ${execStart} ${command} --json
${env}
# Output goes to the journal; the envelope carries no secrets.
NoNewPrivileges=yes
PrivateTmp=yes
`;
  const timer = (description: string, time: string, serviceName: string) => `# Generated by radar market schedule install — do not edit by hand.
[Unit]
Description=${description}

[Timer]
OnCalendar=${onCalendar(time)}
Persistent=true
Unit=${serviceName}

[Install]
WantedBy=timers.target
`;
  return {
    "short-drama-radar-market-analyze.service":
      service("market-analyze", "short-drama-radar market: analyze the previous complete local day", "market analyze"),
    "short-drama-radar-market-analyze.timer":
      timer("short-drama-radar market: analyze before the daily brief", MARKET_SCHEDULE_TIMES.analyze, "short-drama-radar-market-analyze.service"),
    "short-drama-radar-market-brief.service":
      service("market-brief", "short-drama-radar market: freeze the daily market brief", "market brief build", ["short-drama-radar-market-analyze.service"]),
    "short-drama-radar-market-brief.timer":
      timer("short-drama-radar market: brief freeze at the configured local time", MARKET_SCHEDULE_TIMES.brief, "short-drama-radar-market-brief.service"),
  };
}

export const MARKET_SCHEDULE_NEXT_STEPS = [
  "systemctl --user daemon-reload",
  "systemctl --user enable --now short-drama-radar-market-analyze.timer short-drama-radar-market-brief.timer",
  "systemctl --user list-timers 'short-drama-radar-market-*'",
];

// Optional owner hook for the PG archive sync (radar market sync --to pg).
// Sync is manual by default: `install` never generates or enables a sync
// timer, and sync is outside the cutoff/freeze semantics — a late sync only
// means the archive replica lags, never that the SQLite source is affected.
// The owner MAY append their own unit after market-brief, e.g.:
//
//   [Unit]
//   Description=short-drama-radar market: archive sync to PostgreSQL
//   After=short-drama-radar-market-brief.service
//   Wants=short-drama-radar-market-brief.service
//
//   [Service]
//   Type=oneshot
//   ExecStart=/usr/bin/flock -w 600 %h/.short-drama-radar/radar.lock <execStart> market sync --to pg --json
//   Environment=RADAR_HOME=%h/.short-drama-radar
//   # RADAR_PG_URL belongs in a user-level EnvironmentFile, never in the unit.
//
// Enabling any such unit is an explicit owner action, like every other timer.
export const MARKET_SCHEDULE_SYNC_HOOK = {
  command: "radar market sync --to pg",
  runs_after: "short-drama-radar-market-brief.service",
  generated: false,
  enabled: false,
  note: "Optional owner hook: install never writes or enables a sync timer; the owner may append their own unit after market-brief. Sync is outside cutoff/freeze semantics — a late sync only leaves the archive replica behind.",
} as const;

// Which readiness states may be collected by a scheduled observation pass.
// planned/identity_verified have no verified sample; blocked is explicitly
// out. Nothing here bypasses a qualification decision.
const OBSERVABLE_READINESS: readonly SourceReadiness[] = ["sample_verified", "qualified"];

export interface MarketSourceRunState {
  source_ref: string;
  readiness: SourceReadiness;
  /** Last attempt time of any outcome, used only for ordering/reporting. */
  last_attempt_at?: string | null;
  /** Risk-control cooldown (login failure / captcha); observation is skipped until it passes. */
  cooldown_until?: string | null;
}

export interface MarketObservationPlan {
  spec: "radar.market_observation_plan.v1";
  policy: typeof MARKET_OBSERVE_POLICY;
  waves: string[][];
  skipped: Array<{ source_ref: string; reason: "qualification_pending" | "blocked" | "risk_control_cooldown" }>;
  attempts_per_source: number;
  retry_backoff_ms: number[];
}

// Pure run plan: eligible sources in deterministic order, executed in
// concurrency-bounded waves. Replay after a suspend/resume produces the same
// plan for the still-eligible sources — batch digests keep re-runs from
// duplicating observations (see repository.saveObservationBatch).
export function planMarketObservationRun(states: MarketSourceRunState[], now = new Date()): MarketObservationPlan {
  if (!Number.isFinite(now.getTime())) throw new Error("planMarketObservationRun requires a valid clock.");
  const skipped: MarketObservationPlan["skipped"] = [];
  const eligible: MarketSourceRunState[] = [];
  for (const state of states) {
    if (state.cooldown_until && Date.parse(state.cooldown_until) > now.getTime()) {
      skipped.push({ source_ref: state.source_ref, reason: "risk_control_cooldown" });
    } else if (state.readiness === "blocked") {
      skipped.push({ source_ref: state.source_ref, reason: "blocked" });
    } else if (!OBSERVABLE_READINESS.includes(state.readiness)) {
      skipped.push({ source_ref: state.source_ref, reason: "qualification_pending" });
    } else {
      eligible.push(state);
    }
  }
  eligible.sort((a, b) =>
    a.last_attempt_at === b.last_attempt_at
      ? a.source_ref.localeCompare(b.source_ref)
      : (a.last_attempt_at ? Date.parse(a.last_attempt_at) : 0) - (b.last_attempt_at ? Date.parse(b.last_attempt_at) : 0));
  const waves: string[][] = [];
  for (let i = 0; i < eligible.length; i += MARKET_OBSERVE_POLICY.global_concurrency) {
    waves.push(eligible.slice(i, i + MARKET_OBSERVE_POLICY.global_concurrency).map(s => s.source_ref));
  }
  return {
    spec: "radar.market_observation_plan.v1",
    policy: MARKET_OBSERVE_POLICY,
    waves,
    skipped,
    attempts_per_source: 1 + MARKET_OBSERVE_POLICY.max_read_retries,
    retry_backoff_ms: [...MARKET_OBSERVE_POLICY.retry_backoff_ms],
  };
}

export type MarketSourceRunErrorCode =
  | "source_unavailable"
  | "source_auth_required"
  | "source_risk_control"
  | "source_timeout";

export interface MarketSourceRunResult {
  source_ref: string;
  outcome: "observed" | "failed" | "incomplete";
  error_code?: MarketSourceRunErrorCode;
  completed_at?: string;
}

export interface MarketRunFreezeDecision {
  spec: "radar.market_run_freeze.v1";
  freeze: true;
  brief_status: "ready" | "degraded" | "empty";
  incomplete_sources: string[];
  failed_sources: string[];
  reasons: string[];
}

// Cutoff decision: a source task that has not finished by the cutoff never
// blocks the edition — the brief freezes partial with named gaps. Bounded
// failure is the honest state; "waiting a bit longer" is not available.
export function resolveMarketRunFreeze(results: MarketSourceRunResult[], opts: { cutoff: string }): MarketRunFreezeDecision {
  const cutoffMs = Date.parse(opts.cutoff);
  if (!Number.isFinite(cutoffMs)) throw new Error("resolveMarketRunFreeze requires a valid cutoff.");
  const incomplete = results.filter(r => r.outcome === "incomplete" ||
    (r.completed_at !== undefined && Date.parse(r.completed_at) > cutoffMs));
  const failed = results.filter(r => r.outcome === "failed");
  const reasons: string[] = [];
  if (incomplete.length) reasons.push("Source tasks did not finish before the cutoff; the edition froze without them.");
  if (failed.length) reasons.push("Failed sources are reported per source; other sources still contributed.");
  const contributing = results.filter(r => r.outcome === "observed");
  return {
    spec: "radar.market_run_freeze.v1",
    freeze: true,
    brief_status: contributing.length ? (incomplete.length || failed.length ? "degraded" : "ready") : "empty",
    incomplete_sources: incomplete.map(r => r.source_ref),
    failed_sources: failed.map(r => r.source_ref),
    reasons,
  };
}

export type RetryDecision = { retry: true; delay_ms: number } | { retry: false; cooldown_hours?: number; reason: string };

// Read-only transport failures retry with the bounded backoff; login and
// risk-control failures never retry automatically and enter the 24h cooldown.
export function marketRetryDecision(errorCode: MarketSourceRunErrorCode, attempt: number): RetryDecision {
  if (errorCode === "source_auth_required" || errorCode === "source_risk_control") {
    return { retry: false, cooldown_hours: MARKET_OBSERVE_POLICY.risk_control_cooldown_hours,
      reason: "Login or risk-control failures never auto-retry; owner review is required." };
  }
  if (attempt >= 1 + MARKET_OBSERVE_POLICY.max_read_retries) {
    return { retry: false, reason: "Read-only retry budget exhausted for this source." };
  }
  return { retry: true, delay_ms: MARKET_OBSERVE_POLICY.retry_backoff_ms[attempt - 1] ?? MARKET_OBSERVE_POLICY.retry_backoff_ms.at(-1)! };
}
