import { join } from "node:path";
import type { RadarConfig } from "./config.ts";

// Systemd user scheduler wiring. Three oneshot services cover the daily
// cycle: collect runs twice (spread deltas need two passes), score once, and
// the card freeze/handoff runs at 08:55/08:59 for the external delivery
// owner. Unit content is pure and golden-tested; installation is explicit.

export interface ScheduleUnits {
  [unitName: string]: string;
}

// Normalize "HH:MM" config values to the full OnCalendar form.
function onCalendar(time: string): string {
  const m = time.match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return `*-*-* ${time}`;
  return `*-*-* ${String(m[1]).padStart(2, "0")}:${m[2]}:00`;
}

export function buildScheduleUnits(cfg: RadarConfig, execStart: string): ScheduleUnits {
  const env = [
    `Environment=RADAR_HOME=%h/.short-drama-radar`,
    systemdEnvironment("PATH", process.env.PATH ?? "/usr/local/bin:/usr/bin:/bin"),
    ...(process.env.FIRECRAWL_BASE_URL ? [`Environment=FIRECRAWL_BASE_URL=${process.env.FIRECRAWL_BASE_URL}`] : []),
  ].join("\n");

  const service = (name: string, description: string, command: string) => `# Generated by radar schedule install — do not edit by hand.
[Unit]
Description=${description}

[Service]
Type=oneshot
ExecStart=${execStart} ${command} --json
${env}
# Output goes to the journal; the envelope carries no secrets.
NoNewPrivileges=yes
PrivateTmp=yes
`;

  const timer = (name: string, description: string, calendars: string[], service: string) => `# Generated by radar schedule install — do not edit by hand.
[Unit]
Description=${description}

[Timer]
${calendars.map((c) => `OnCalendar=${onCalendar(c)}`).join("\n")}
Persistent=true
Unit=${service}

[Install]
WantedBy=timers.target
`;

  return {
    "short-drama-radar-xhs.service": `# Generated by radar schedule install — do not edit by hand.
[Unit]
Description=short-drama-radar: xiaohongshu MCP backend
ConditionPathExists=%h/.agent-reach/tools/xiaohongshu-mcp

[Service]
Type=simple
WorkingDirectory=%h/.agent-reach/xiaohongshu
ExecStart=%h/.agent-reach/tools/xiaohongshu-mcp -headless=true -port 127.0.0.1:18060
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
PrivateTmp=yes

[Install]
WantedBy=default.target
`,
    "short-drama-radar-collect.service": service("collect", "short-drama-radar: collect pass (Layer 0-3 fetch)", "collect"),
    "short-drama-radar-collect.timer": timer("collect", "short-drama-radar: collect at the two morning passes", [cfg.schedule.collect1, cfg.schedule.collect2], "short-drama-radar-collect.service"),
    "short-drama-radar-score.service": service("score", "short-drama-radar: score the collected day", "score"),
    "short-drama-radar-score.timer": timer("score", "short-drama-radar: score after the second collect pass", [cfg.schedule.score], "short-drama-radar-score.service"),
    "short-drama-radar-card.service": service("card", "short-drama-radar: freeze card.v1 payload for the delivery owner", "card"),
    "short-drama-radar-card.timer": timer("card", "short-drama-radar: card freeze + send handoff windows", [cfg.schedule.freeze, cfg.schedule.send], "short-drama-radar-card.service"),
  };
}

export const SCHEDULE_NEXT_STEPS = [
  "systemctl --user daemon-reload",
  "systemctl --user enable --now short-drama-radar-xhs.service short-drama-radar-collect.timer short-drama-radar-score.timer short-drama-radar-card.timer",
  "systemctl --user list-timers 'short-drama-radar-*'",
];

export function systemdUserDir(home: string): string {
  return join(home, ".config", "systemd", "user");
}

function systemdEnvironment(name: string, value: string): string {
  const escaped = value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("%", "%%");
  return `Environment="${name}=${escaped}"`;
}
